' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class DocumentCategories

    <JsonProperty("document_categories")>
    Public Property DocumentCategories As DocumentCategory()

End Class
