' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class IssueStatuses

    <JsonProperty("issue_statuses")>
    Public Property IssueStatuses As IssueStatus()

End Class
