' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class Issue

    <JsonProperty("id")>
    Public Property Id As Integer

    <JsonProperty("project")>
    Public Property Project As Project

    <JsonProperty("tracker")>
    Public Property Tracker As Tracker

    <JsonProperty("status")>
    Public Property Status As Status

    <JsonProperty("priority")>
    Public Property Priority As Priority

    <JsonProperty("author")>
    Public Property Author As Author

    <JsonProperty("assigned_to")>
    Public Property AssignedTo As AssignedTo

    <JsonProperty("fixed_version")>
    Public Property FixedVersion As FixedVersion

    <JsonProperty("subject")>
    Public Property Subject As String

    <JsonProperty("start_date")>
    Public Property StartDate As String

    <JsonProperty("due_date")>
    Public Property DueDate As String

    <JsonProperty("done_ratio")>
    Public Property DoneRatio As Integer

    <JsonProperty("custom_fields")>
    Public Property CustomFields As CustomField()

    <JsonProperty("created_on")>
    Public Property CreatedOn As String

    <JsonProperty("updated_on")>
    Public Property UpdatedOn As String

    <JsonProperty("story_points")>
    Public Property StoryPoints As Double?

    <JsonProperty("description")>
    Public Property Description As String

    <JsonProperty("parent")>
    Public Property Parent As Parent

    <JsonProperty("estimated_hours")>
    Public Property EstimatedHours As Double?

    <JsonProperty("category")>
    Public Property Category As Category

End Class
