' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class IssueCategory

    <JsonProperty("id")>
    Public Property Id As Integer

    <JsonProperty("project")>
    Public Property Project As Project

    <JsonProperty("name")>
    Public Property Name As String

End Class
