' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class IssuePriorities

    <JsonProperty("issue_priorities")>
    Public Property IssuePriorities As IssuePriority()

End Class
