' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class Membership

    <JsonProperty("id")>
    Public Property Id As Integer

    <JsonProperty("project")>
    Public Property Project As Project

    <JsonProperty("user")>
    Public Property User As User

    <JsonProperty("roles")>
    Public Property Roles As Role()

    <JsonProperty("group")>
    Public Property Group As Group

End Class
