' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class Project

    <JsonProperty("id")>
    Public Property Id As Integer

    <JsonProperty("name")>
    Public Property Name As String

    <JsonProperty("identifier")>
    Public Property Identifier As String

    <JsonProperty("description")>
    Public Property Description As String

    <JsonProperty("status")>
    Public Property Status As Integer

    <JsonProperty("custom_fields")>
    Public Property CustomFields As CustomField()

    <JsonProperty("created_on")>
    Public Property CreatedOn As String

    <JsonProperty("updated_on")>
    Public Property UpdatedOn As String

    <JsonProperty("is_public")>
    Public Property IsPublic As Boolean?

End Class
