' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class TimeEntryActivities

    <JsonProperty("time_entry_activities")>
    Public Property TimeEntryActivities As TimeEntryActivity()

End Class
