' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class Version

    <JsonProperty("id")>
    Public Property Id As Integer

    <JsonProperty("project")>
    Public Property Project As Project

    <JsonProperty("name")>
    Public Property Name As String

    <JsonProperty("description")>
    Public Property Description As String

    <JsonProperty("status")>
    Public Property Status As String

    <JsonProperty("due_date")>
    Public Property DueDate As String

    <JsonProperty("sharing")>
    Public Property Sharing As String

    <JsonProperty("created_on")>
    Public Property CreatedOn As String

    <JsonProperty("updated_on")>
    Public Property UpdatedOn As String

End Class
