' Generated by Xamasoft JSON Class Generator
' http://www.xamasoft.com/json-class-generator

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports Newtonsoft.Json.Linq

Public Class Versions

    <JsonProperty("versions")>
    Public Property Versions As Version()

    <JsonProperty("total_count")>
    Public Property TotalCount As Integer

End Class
